import { z } from 'zod';


export const binStatusTypeEnum = z.enum(['EMPTY', 'PARTIAL', 'FULL', 'UNAVAILABLE']);

export const createBinSchema = z.object({
    latitude: z.number()
        .min(-90, 'Latitude must be between -90 and 90')
        .max(90, 'Latitude must be between -90 and 90')
        .refine(
            (val) => {
                // Check if the number has at most 6 decimal places
                const decimalPlaces = (val.toString().split('.')[1] || '').length;
                return decimalPlaces <= 6;
            },
            'Latitude must have at most 6 decimal places'
        ),
    longitude: z.number()
        .min(-180, 'Longitude must be between -180 and 180')
        .max(180, 'Longitude must be between -180 and 180')
        .refine(
            (val) => {
                // Check if the number has at most 6 decimal places
                const decimalPlaces = (val.toString().split('.')[1] || '').length;
                return decimalPlaces <= 6;
            },
            'Longitude must have at most 6 decimal places'
        ),
    area_id: z.string().uuid(),
    user_id: z.string().uuid(),
    qr_code_link: z.string().url().nullish(), // Accept null, undefined, or valid URL
    // Don't include created_at/updated_at in creation schema - these should be auto-generated by DB
    bin_status: binStatusTypeEnum.default('EMPTY'),
});

/**
 * Schema for validating QR code before bin status update
 * Security: Ensures collector physically scanned the bin's QR code
 */
export const validateQRCodeSchema = z.object({
    binId: z.string().uuid('Invalid bin ID format'),
    qrCodeLink: z.string()
        .url('Invalid QR code link format')
        .startsWith('ecosync://bin/', 'QR code must be a valid EcoSync bin QR code'),
});
